### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by hmseeb** [RukshanJS/flutter-fuse#5]
Flutter Fuse: Import fixing operation timed out. Some imports may not have been fixed. I keep getting this error over and over in each and every file.

**Comment by RukshanJS** [comment]
> Flutter Fuse: Import fixing operation timed out. Some imports may not have been fixed. I keep getting this error over and over in each and every file.

Hi @hmseeb, thanks a lot for raising this issue. I had put a hard coded time duration for which the importing process is done and if it doesn't work within that time, the timeout is thrown. 

I'll work on this and give a fix within this week 😃

**Comment by hmseeb** [comment]
It never starts importing in the first place let alone running the command twice the fix the rest.

**Comment by RukshanJS** [comment]
> It never starts importing in the first place let alone running the command twice the fix the rest.

I'm really sorry for this. I'll try to reproduce and push a fix. Thanks again!

**Comment by hmseeb** [comment]
you're welcome :) kindly update it asap.. I love using this extension. It really boosts my productivity.

**Comment by RukshanJS** [comment]
> you're welcome :) kindly update it asap.. I love using this extension. I really boosts my productivity.

Hi @hmseeb  Sorry for the late reply. The latest version v0.0.2 of the extension should have this fixed. It's solved with #6 Please reply to this so that I can close it. Thanks!
